### ISSUE TITLE
Crashes when tying to open an image

### ISSUE THREAD

**Issue by YouriStudent** [adrianboguszewski/debug-image-viewer#2]
When trying to view an image using the plugin with the debugger I got the following error:
```
java.lang.IllegalArgumentException: Illegal base64 character 2e
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:852)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:570)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:593)
	at a.a.a.d.c.b.h.a(SourceFile:188)
	at a.a.a.d.c.a$b.run(SourceFile:20)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:49)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:501)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:466)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:97)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:92)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
os: kubuntu 22.04
PyCharm 2024.2.1 (Professional Edition)
plugin version 4.1.0

**Comment by adrianboguszewski** [comment]
Is it possible to share a snippet of code that produces the image you want to show?

**Comment by YouriStudent** [comment]
It wil do it with all the images I try.
Here is an code sample with the used image

```python
import cv2

img = cv2.imread('dummy.jpg')

print("hello")
```
I have put the debugger on the print("hello") and then clicked view image and got the error
![dummy](https://github.com/user-attachments/assets/fcce3a54-d3b8-4b26-82cc-d44c95643497)

**Comment by adrianboguszewski** [comment]
Could you go to the plugin settings, verify if you have "anonymous usage statistics" checked, and provide your ID (just below the checkbox)? Then I'll find you in the database and check your error.

**Comment by adrianboguszewski** [comment]
Hey @YouriStudent. I found the issue. JetBrains, in 2024.2, has reduced the default buffer size when loading variables from the debugger. If I fixed this by simply using a smaller buffer, the loading time would be very long. 

The only workaround, before I design a new robust solution, is to use PyCharm 2024.1 when using the plugin with a remote interpreter (local interpreter = no problem).

**Comment by adrianboguszewski** [comment]
This issue is partially fixed in Debug Image Viewer 4.2.0 by reducing the buffer size. To have a final fix I'm waiting for this [issue](https://youtrack.jetbrains.com/issue/PY-75638) to be fixed by JetBrains.

**Comment by adrianboguszewski** [comment]
Finally, it is fully fixed in the version of 4.2.2.
