### ISSUE TITLE
Cannot display image：llegalArgumentException: lllegal base64 character 2e

### ISSUE THREAD

**Issue by YueyueBird-su** [adrianboguszewski/debug-image-viewer#4]
![image](https://github.com/user-attachments/assets/13e1d068-f558-4e5b-9fff-dc02f1d40ffc)
![image](https://github.com/user-attachments/assets/ac39bcf2-d63e-4eb1-a540-526cbbc4b73d)

java.lang.IllegalArgumentException: Illegal base64 character 2e
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:852)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:570)
	at java.base/java.util.Base64$Decoder.decode(Base64.java:593)
	at a.a.a.d.c.b.h.a(SourceFile:188)
	at a.a.a.d.c.a$b.run(SourceFile:20)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:49)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:501)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:466)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:92)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:97)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:92)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:464)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by adrianboguszewski** [comment]
Hey @YueyueBird-su. I bet you use a remote interpreter, don't you?

Could you go to the plugin settings, verify if you have "anonymous usage statistics" checked, and provide your ID (just below the checkbox)? Then I'll find you in the database and check your error.

**Comment by YueyueBird-su** [comment]
Hi there!
My development environment is Win11+WSL2, and I use the conda environment in WSL2 to debug Windows code in the pycharm compiler.
And I've unchecked ‘Send anonymous usage statistics’.
My ID  is ce94d0de0fed4f860f45e10ad63fef6f.
![image](https://github.com/user-attachments/assets/d177006d-e2a7-42c8-9d21-090538b97ab2)

Thank you for your help!

**Comment by adrianboguszewski** [comment]
Ok, I found you in the database. Let me work on it.

Btw. if you uncheck 'Send anonymous usage statistics' future plugin errors won't be reported to me.

**Comment by Dev-Jahn** [comment]
@adrianboguszewski
I've used the plugin for a while, and it was very useful so I purchased the premium license.
But after purchase I've faced the bug when using remote interpreter.
I know you mentioned it in github issue and suggested using 2024.1, but there's critical issue in 2024.1 that does not allow me to launch debugger with remote interpreter.
Is there any quick fix by increasing buffer size or anything hacky I can do?
I really need the plugin for current development asap.

**Comment by adrianboguszewski** [comment]
Hey @Dev-Jahn. The problem comes from the Intellij Platform SDK and was reported 2 months ago here: https://youtrack.jetbrains.com/issue/PY-75638/Debugger-trims-value-copy-of-a-variable. However, JetBrains hasn't fixed it yet. To mitigate this I'd need to shrink the buffer 4000x (sic!) and image downloading time would increase 10x. If possible, please use 2023.3, then.

I'm working to find a better workaround. Sorry for that :/

**Comment by Dev-Jahn** [comment]
@adrianboguszewski Thx for fast response.
Somehow, I've wiped all remote interpreter configs and managed to fix the issue in 2024.1.
It works like charm in 2024.1.
Hope Jetbrains fix the buffer issue soon though.
Cheers :)

**Comment by adrianboguszewski** [comment]
This issue is partially fixed in Debug Image Viewer 4.2.0 by reducing the buffer size. To have a final fix I'm waiting for this [issue](https://youtrack.jetbrains.com/issue/PY-75638) to be fixed by JetBrains.

**Comment by fenneishi** [comment]
![image](https://github.com/user-attachments/assets/934cc7ad-c35b-43d5-8f31-39af3632224a)
So, has this issue been resolved now?

**Comment by fenneishi** [comment]
![image](https://github.com/user-attachments/assets/171b6386-612d-4ea0-8a7e-747cb721d888)

> I've upgraded PyCharm to 2024.3.1, and it seems to be able to load frame from the server, but it's very slow. Is this normal?

**Comment by fenneishi** [comment]
> ![image](https://private-user-images.githubusercontent.com/33345538/398081894-171b6386-612d-4ea0-8a7e-747cb721d888.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5Mzg1ODQsIm5iZiI6MTczNDkzODI4NCwicGF0aCI6Ii8zMzM0NTUzOC8zOTgwODE4OTQtMTcxYjYzODYtNjEyZC00ZWEwLThhN2UtNzQ3Y2I3MjFkODg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA3MTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4NmQ4ZjlkYTc4M2I3ZTk4NWJiYWZlZmI0YWQ5ODkxYTZmNzM3ZGI2NDg0MjY5ODRiYTE5NjQ0ZmUwZWI5MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZS0e3QG6U0fYk7J1lG-q4_ZieneAuaVOEE4zUgm_t7w)
> 
> > I've upgraded PyCharm to 2024.3.1, and it seems to be able to load frame from the server, but it's very slow. Is this normal?

![image](https://github.com/user-attachments/assets/7e96006c-5b76-484b-8af8-ec66d9cbf9f6)
the progress bar after 5 minutes

**Comment by adrianboguszewski** [comment]
@fenneishi unfortunately, it's expected :/
JetBrains introduced a bug in 2024.2 and then I had to reduce the buffer. It appears the problem is fixed now. However, the new version of PyCharm hasn't been released yet. 

I'll improve that as soon as they release the fix. Sorry for that :/

Reference: https://youtrack.jetbrains.com/issue/PY-75638/Debugger-trims-value-copy-of-a-variable

**Comment by eliahuhorwitz** [comment]
When will the slow loading time will be fixed? The plugin is unusable at the moment, it takes minutes to view an image. Is there any workaround (that does not require me to downgrade the pycharm version)?

**Comment by adrianboguszewski** [comment]
Hey @eliahuhorwitz. The [bug described above](https://youtrack.jetbrains.com/issue/PY-75638/Debugger-trims-value-copy-of-a-variable) was fixed in 243.23064, according to JetBrains. However, they haven't released it yet. I'll fix it as soon as the new version is available. The latest available version is 243.22562.220. 

The only possible workaround is downgrading to 2024.1 or using a local interpreter.

**Comment by fenneishi** [comment]
Found the solution—JetBrains Gateway. Debug-image-viewer works fine and fast in Gateway.
By the way, JetBrains Gateway is awesome and solved most of my remote dev problems.

**Comment by fenneishi** [comment]
> Found the solution—JetBrains Gateway. Debug-image-viewer works fine and fast in Gateway. By the way, JetBrains Gateway is awesome and solved most of my remote dev problems.

Quick tip: Before clicking 'View as Image', expand the 'array' property to make JetBrains fetch the data from the remote server.
![image](https://github.com/user-attachments/assets/1b11c0fe-1fce-4076-9451-2fa42b836f41)
![image](https://github.com/user-attachments/assets/ef6d1f92-949a-4ac0-b4b1-bc38b9bd8f3f)
![image](https://github.com/user-attachments/assets/f8fb4adf-da78-4a21-a9a4-fbb8e2d286d7)

**Comment by adrianboguszewski** [comment]
Wow! @fenneishi that looks good. Let me test it and see if we can do anything in Pycharm inspiring from Gateway :)

**Comment by fenneishi** [comment]
Looking forward ...

**Comment by adrianboguszewski** [comment]
@fenneishi I'm happy to announce I found the workaround and the new version (4.2.2) with the fix for the above has been released! Could you install it in Pycharm and verify it works as expected for you?
